name: Google Sheets Update with R

on:
  workflow_dispatch: # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Lifisher_Sheet_Secrets # 指定环境名称

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install system dependencies for R
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libxml2-dev

      - name: Cache R packages
        id: cache-r-packages
        uses: actions/cache@v3
        with:
          path: ~/.R/library
          key: r-packages-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            r-packages-

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("dplyr", "googlesheets4"), repos="https://cloud.r-project.org")'

      - name: Create credentials file
        run: echo '${{ secrets.SHEET_KEY }}' > credentials.json

      - name: Run R script
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: Rscript Update_Sheets.R

      - name: Remove credentials file
        run: rm credentials.json

      - name: Notify on success
        if: success()
        run: |
          echo "R script ran successfully!"

      - name: Notify on failure
        if: failure()
        run: |
          echo "R script failed!"
