name: Google Sheets Update with rpy2

on:
  push:
    branches:
      - main
  workflow_dispatch: # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: LIFISHER_SECRETS # 指定环境名称
    env:
      TZ: Asia/Shanghai # 设置时区为北京时间 (UTC+8)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install system dependencies for R
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libxml2-dev

      - name: Cache R packages
        id: cache-r-packages
        uses: actions/cache@v3
        with:
          path: ~/.R/library
          key: r-packages-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            r-packages-

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("dplyr", "ggplot2"), repos="https://cloud.r-project.org")'

      - name: Install Python dependencies
        run: |
          pip install pandas gspread oauth2client rpy2

      - name: Create credentials file
        run: echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > credentials.json

      - name: Run Python script
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python Update_Sheet.py

      - name: Remove credentials file
        run: rm credentials.json

      - name: Notify on success
        if: success()
        run: |
          echo "Python script ran successfully!"

      - name: Notify on failure
        if: failure()
        run: |
          echo "Python script failed!"
